### ISSUE TITLE
problem with davis api tool

### ISSUE THREAD

**Issue by belidi** [uajqq/weewx-davishealthapi#5]
I have this 

"api-secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", #REPLACE THIS WITH YOUR API SECRET
                ^
SyntaxError: invalid syntax
or 

"api_secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", #REPLACE THIS WITH YOUR API SECRET
  "t": int(time.time())

and in the log : 
ser.davishealthapi: No valid historical  API data recieved. Double-check API key/secret and station id. Error is: 'sensors'
Jan  4 17:30:15 raspberrypi weewx[12777] ERROR user.davishealthapi: The API data returned was: {'code': '400', 'message': 'Station ID contains non-numerical characters'}
Jan  4 17:30:16 raspberrypi weewx[12777] ERROR user.davishealthapi: No valid current API data recieved. Double-check API key/secret and station id. Error is: 'sensors'
Jan  4 17:30:16 raspberrypi weewx[12777] ERROR user.davishealthapi: The API data returned was: {'code': '400', 'message': 'Station ID contains non-numerical characters'}
Jan  4 17:30:16 raspberrypi weewx[12777] INFO weewx.manager: Added record 2021-01-04 17:30:15 CET (1609777815) to database 'davishealthapi.sdb'

**Comment by uajqq** [comment]
With the old tool, you had to open `davis_api_tool.py` in an editor and replace those API values yourself--see README.md. I just pushed an improved version that asks for the API keys interactively, so this should no longer be an issue.
